services:
  ollamalitellm:
    image: ollamalitellm:latest
    build: /containers/ollamalitellm
    container_name: OllamaLiteLLM
    ports:
      - "4000:4000"
      - "5000:5000"
    networks:
      - ollamalitellm
      - mongodb
    volumes:
      -  LLMS:/root/.ollama
      - ./containers/ollamalitellm:/app
      - ./litellm-config.yaml:/app/config.yaml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      MONGO_CONNSTRING: mongodb://${MONGOUSER}:${MONGOPASS}@mongo:27017/

  autogenstudio:
    container_name: AutogenStudio
    image: autogenstudio:latest
    build: /containers/autogenstudio
    ports:
      - "8081:8081"
    networks:
      - ollamalitellm
      - mongodb
    volumes:
      - ./containers/autogenstudio:/app
      - AGS:/home/autogen
      - AGS:/home/.autogenstudio
    environment:
      MONGO_CONNSTRING: mongodb://${MONGOUSER}:${MONGOUSER}@mongo:27017/

  mongo:
    image: mongo
    container_name: MongoDB
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGOADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGOADMIN_PASS}
      MONGO_CONNSTRING: mongodb://${MONGOADMIN_USER}:${MONGOADMIN_PASS}@mongo:27017/
    ports:
      - 27017:27017
    networks:
      - mongodb
    volumes:
      - mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    container_name: MongoExpress
    networks:
      - mongodb
    ports:
      - 8082:8081 # 8081 is already used by autogenstudio
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGOADMIN_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGOADMIN_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGOADMIN_USER}:${MONGOADMIN_PASS}@mongo:27017/
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_CONNSTRING: mongodb+srv://${MONGOADMIN_USER}:${MONGOADMIN_PASS}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
      
networks:
  ollamalitellm:
    driver: bridge
  mongodb:
    driver: bridge

volumes:
  LLMS:
  AGS:
  mongodb: